### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by shimatai** [LukasLen/Privacy-Extension-For-WhatsApp-Web#11]
Please, implement a dark mode option.

Another way is to offer themes, dark mode, light mode, blue mode, green mode etc.

Thanks!

**Comment by LukasLen** [comment]
Hi!
Just for clarification: Do you mean a dark mode for the extension or WhatsApp Web itself?

**Comment by shimatai** [comment]
Yes. For example, the extension WA Web Plus has a dark mode, that turns the whole " web.whatsapp.com" in a dark site, with white text and dark background.

**Comment by Revocation** [comment]
Dark mode for WhatsApp Web should be great. Anyway, the add-on (I'm Firefox user) is very usefull. Congratulations.

**Comment by LukasLen** [comment]
I get you, however, there are other extensions taking care of this. This feature wouldn't fit with what the focus of the privacy extension is.

**Comment by OJ7** [comment]
In case others are looking for an option, I've been using [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) for dark mode across all websites.
