### ISSUE TITLE
Add an option to adjust blur amount

### ISSUE THREAD

**Issue by OJ7** [LukasLen/Privacy-Extension-For-WhatsApp-Web#12]
**Is your feature request related to a problem? Please describe.**
I would like to be able to blur certain elements but to a certain amount so that they're partially visible. 

**Describe the solution you'd like**
An option to adjust blur amount (e.g. using a percentage).

**Describe alternatives you've considered**
I was manually doing this using the Styler extension and just came about this extension. Here's the CSS I used:

```
._1Wn_k {
    color: transparent;
    text-shadow: 0 0 4px rgba(0,0,0,0.5);
}


._1Wn_k > span > img {
	filter: blur(4px)
}```

**Comment by Tgentil** [comment]
Feature added by #87
