### ISSUE TITLE
Add an option see at least the 3 last viewed messages in chat u want to see instantaneously 

### ISSUE THREAD

**Issue by Xarchuser** [LukasLen/Privacy-Extension-For-WhatsApp-Web#21]
Would be interesting a custom option to view how many messages u want in chat without compromising the rest of conversation .

**Comment by kirwa-KO** [comment]
you can use this extention [Whatsapp Blur](https://chrome.google.com/webstore/detail/whatsapp-blur/nlekcjbieonbccodmkangkiiopcmchol) that can blur all messages except of last 3 messages
