### ISSUE TITLE
Add blur effect for sent or received documents

### ISSUE THREAD

**Issue by islam-qalqul** [LukasLen/Privacy-Extension-For-WhatsApp-Web#24]
The document message or its name is not getting blurred. Please add this. 
![WhatsApp](https://user-images.githubusercontent.com/113340974/194296205-79fbd01b-2e05-4dc1-9263-24c7e4a8e5a5.png)

**Comment by kirwa-KO** [comment]
you can use this extention [Whatsapp Blur](https://chrome.google.com/webstore/detail/whatsapp-blur/nlekcjbieonbccodmkangkiiopcmchol) that can blur receive and sent documents

**Comment by LukasLen** [comment]
Fixed with 84bb27ec7ec60314a3b8c4a0d7c7d47cfb781d1e
