### ISSUE TITLE
Blur whatsapp on idle

### ISSUE THREAD

**Issue by batflarrow** [LukasLen/Privacy-Extension-For-WhatsApp-Web#25]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm just frustrated with the blur.

**Describe the solution you'd like**
It would be great if you could add an option to specify a timeout for idle time and after that timeout expires WhatsApp web automatically gets blurred.

**Comment by deaf27577** [comment]
![Screenshot_2023-01-30-20-28-07-675_com whatsapp w4b](https://user-images.githubusercontent.com/123980137/215550126-c6442e6b-e15f-4cac-b9f4-bfb43c96d6b3.jpg)





+967 778 881 434

**Comment by Sumonmiahcml78** [comment]
Duplicate of #27577

**Comment by Tgentil** [comment]
Feature added by #87
