### ISSUE TITLE
Blur users name in quoted messages

### ISSUE THREAD

**Issue by infernalMan** [LukasLen/Privacy-Extension-For-WhatsApp-Web#26]
**Is your feature request related to a problem? Please describe.**
When I deactivate blur all messages in chat, the user name in the quoted messages still displayed eventhough I activate blur users names.

**Describe the solution you'd like**
The users name in quoted messages blurred just like the profile names.

**Describe alternatives you've considered**
All quoted message in chat bubble gets blurred (not just the names)

**Additional context**
-

**Comment by LukasLen** [comment]
Fixed with 84bb27ec7ec60314a3b8c4a0d7c7d47cfb781d1e
