### ISSUE TITLE
does this really not work in the latest version?

### ISSUE THREAD

**Issue by binsarjr** [LukasLen/Privacy-Extension-For-WhatsApp-Web#30]

**Comment by delfaaan** [comment]
Yes, this does not work on the latest version, only blur photos, maybe other media too.

Please update. Thank you.

**Comment by xdnroot** [comment]
Yes, it doesn't work on Firefox 108.0.2

**Comment by Kiosu** [comment]
I just update my chrome and it doesn't work

Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by dannyvanderzande** [comment]
I downloaded the source and updated it locally to the latest verison of whatsapp web. Pull requests --> #31  #32

**Comment by LukasLen** [comment]
Fixed with 84bb27ec7ec60314a3b8c4a0d7c7d47cfb781d1e
