### ISSUE TITLE
The Last Message preview blur after on the name blur

### ISSUE THREAD

**Issue by NessaRNG** [LukasLen/Privacy-Extension-For-WhatsApp-Web#42]
**Describe the bug**
When i activate the group/name blur the message preview following to blur

![image](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/103401388/60b0a9a8-51d5-4778-a582-8a89b1893c18)

**Comment by UsmanAhmadSaeed** [comment]
I recreated this. When the group/username blur is on, it blurs the last message preview as well, meaning essentially that last message preview blur is affected twice from group/username blur file and last message preview's relevant file.
Further, 
1. The profile picture and username blur doesn't work on business profile's name and picture in user details section.
2. Media preview blur is not working on videos.
3. Message blur resizes the message boxes in chat and makes them oversized.
4. Profile pictures are not blurred in voice messages.

@LukasLen in response to your update on the other thread, I just wanted to say thanks for the update, and that I'd moved to my own fork and have been using that instead with an unlisted firefox only release. I'd be happy to share the latest code if you want. I've tweaked it to my liking, but it's essentially the same with updated selectors. Only difference I noticed so far is that I'm blurring the "about" section too in user details.

Anyways, thanks again. 🙂
