### ISSUE TITLE
[Feature Request] Separate toggle for sidebar user/group names blurring

### ISSUE THREAD

**Issue by bayazidbh** [LukasLen/Privacy-Extension-For-WhatsApp-Web#44]
**Is your feature request related to a problem? Please describe.**
It can be pretty annoying when a coworker, boss, or I'm taking a quick fullscreen screenshot for quick sending, and you have your friends or SO with not-quite-professional names in the screen in the chat list sidebar.

The current name toggle blurs all names, even in main chat pane, which isn't ideal because then I either have to unblur them one by one to check, or just outright disable the name blurring.

**Describe the solution you'd like**in
A separate toggle for sidebar user/group names blurring, or just a toggle for full blurring of chat list sidebar:

<details><summary>Enhancer for Telegram</summary>
<p> 

![image](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/26621899/19bd02a9-9a5c-405a-b84b-9e2d3d845c51)

</p>
</details>

To be quite honest, separation of chat list sidebar and main chat pane blurring toggles and operation in general would be helpful - as in, I could turn full blurring for both, but if I hover main chat pane it'll get unblurred and if I hover chat list only that part would get blurred, much like the "unblur all on app hover" but separate toggles for each panels.

**Describe alternatives you've considered**
I could just turn names blurring on and off when necessary, but that is very annoying especially as I often needs to share screenshots.

**Additional context**

No Names Blurring:

<details><summary>Names Unblurred</summary>
<p> 

![image](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/26621899/08366f63-9426-403c-9133-3f876c9fb051)

</p>
</details>

With names blurring:

<details><summary>Names Blurred</summary>
<p> 

![image](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/26621899/2293fa7c-b977-455c-aa20-67346941d56f)

</p>
</details>

Ideally:

<details><summary>Separated</summary>
<p> 

![out](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/26621899/7aee7808-f5ac-4d0a-a9e4-49d6f6894e13)

</p>
</details>

**Comment by UsmanAhmadSaeed** [comment]
Off-topic:
Hey, was wondering about the details of that Telegram image you linked in the issue. Can you please provide some insight into if that is used on telegram app, and what extension/program was used.

**Comment by bayazidbh** [comment]
@UsmanAhmadSaeed it is called [Enhancer for Telegram](https://mybrowseraddon.com/telegram-desktop.html)
