### ISSUE TITLE
Unable to paste text into message box when this extenstion is enabled (even when toggle off)

### ISSUE THREAD

**Issue by amithm7** [LukasLen/Privacy-Extension-For-WhatsApp-Web#45]
**Describe the bug**
Cannot paste text from Clipboard. But pasting image works though.

**Desktop (please complete the following information):**
 - OS: Linux Debian
 - Browser Firefox 117
 - Version 2.12.1 (extension)

**Comment by LukasLen** [comment]
Hi, I was not able to reproduce the issue. Does it still exist?

**Comment by amithm7** [comment]
Seems to be fixed. :+1:
