### ISSUE TITLE
[Feature Request] Add lock support that requires a password

### ISSUE THREAD

**Issue by w4po** [LukasLen/Privacy-Extension-For-WhatsApp-Web#47]
A lock ability would be much appreciated 😍,
To automatically lock the WhatsApp web page on page load or when being inactive for a minute or so.
Thank you very much for the awesome extension ♥️

**Comment by aryomuzakki** [comment]
actually, Whatsapp already have this feature.
You can access it from **Settings** -> **Privacy** -> **Screen Lock**

And I think this extension didn't need this feature anymore
@w4po

**Comment by LukasLen** [comment]
Closed, as already supported.
