### ISSUE TITLE
won't blur when using /send path on URL

### ISSUE THREAD

**Issue by ticmaidev** [LukasLen/Privacy-Extension-For-WhatsApp-Web#53]
**Describe the bug**

The following wouldn't trigger blur on WhatsApp Web:

https://web.whatsapp.com/send?phone=10000000000

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Firefox

**Additional context**
The extension works great when navigating on https://web.whatsapp.com. But appending a path to it seems to disable the extenstion behavior.

**Comment by LukasLen** [comment]
Hi, version 3.0.1 should fix this. Would you be so kind to check if this is the case?

**Comment by ticmaidev** [comment]
It works and I'm thankful for that.

Although, there's 2 things I should note:

1 - you need to remove `background.service_worker` on Firefox build. I was unable to install, until I've removed it and used `scripts: ["background.js"]`;
2 - apparently, Firefox is now asking users if they want the extension work "when clicked" or "always". "when clicked" seems to be default behavior, which might cause some confusion and less versed people might think this extension is not working. I'm guessing this behaviour has something to do with manifest v3.

_ps: right click on extension to understand what I've described on list item 2_

**Comment by LukasLen** [comment]
Thanks for the valuable feedback, I will work on this.
