### ISSUE TITLE
extention not working anymore for whatsapp

### ISSUE THREAD

**Issue by Akashsinghal261** [LukasLen/Privacy-Extension-For-WhatsApp-Web#55]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LukasLen** [comment]
Can't reproduce this. Should be fixed with dc1799b5a12f620146b4288472f3bd0dfc088578
