### ISSUE TITLE
The extension has stopped blurring 

### ISSUE THREAD

**Issue by Tgentil** [LukasLen/Privacy-Extension-For-WhatsApp-Web#56]
**Describe the bug**  
I've been using the Privacy Extension for WhatsApp Web for a long time and have generally been very satisfied with it. I usually keep the toggle, last message preview, and group/users name options enabled. However, as of today, the extension has stopped blurring. Despite trying various settings, I am unable to blur any content.

**To Reproduce**  
1. Open Chrome and go to WhatsApp Web.
2. Notice that no information (like last messages or group/user names) is being blurred.
3. Try toggling different options on and off in the extension, but observe that nothing changes.
4. I also attempted closing and reopening Chrome, removing and reinstalling the extension, and refreshing the WhatsApp Web page multiple times, but none of these actions resolved the issue.

**Expected behavior**  
Normally, with the extension enabled and the appropriate settings turned on, sensitive information on WhatsApp Web should be blurred for privacy. However, this is currently not happening.

**Screenshots**  
![Captura de tela 2024-03-14 171316](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/88681055/b2eac6e8-9ba9-498a-ba84-02854e706d9a)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home Single Language, Version 23H2
 - Browser: Chrome
 - Version: 122.0.6261.129 (Official Build) (64-bit)

**Additional context**  
I am currently using version 3.1 of the Privacy Extension for WhatsApp Web. This issue is a recent development, as the extension was functioning correctly until today. Any assistance in resolving this would be greatly appreciated, as I rely on this extension for privacy on WhatsApp Web.

**Comment by mclorand** [comment]
I have the same problem

**Comment by roniekas** [comment]
i think its because the css selector is changed

**Comment by nikhilnk2206** [comment]
Facing same issue

**Comment by Tgentil** [comment]
For those experiencing the same issue with the extension not blurring content, could you guys please share your operating system (OS) and browser details? This information could be crucial in identifying a pattern or specific cause behind the problem.

Additionally, I'd like to inform that a colleague of mine, using the same Chrome version and also on Windows and in the same region ( Florianópolis, SC -Brazil),  reports that the extension is functioning normally on their end. This could indicate that the issue might not be universal across all users with similar setups.

To further assist in resolving this issue quickly, I can provide the selector, JS path, full XPath of a message, and the last message of a group. I'm also willing to share a file containing the styles of these elements if it would be helpful.

**Comment by nikhilnk2206** [comment]
Sharing mine , macbook M1 , chrome , country india

**Comment by mclorand** [comment]
> For those experiencing the same issue with the extension not blurring content, could you guys please share your operating system (OS) and browser details? This information could be crucial in identifying a pattern or specific cause behind the problem.
> 
> Additionally, I'd like to inform that a colleague of mine, using the same Chrome version and also on Windows and in the same region ( Florianópolis, SC -Brazil), reports that the extension is functioning normally on their end. This could indicate that the issue might not be universal across all users with similar setups.
> 
> I have also tried disabling all other extensions to check for possible conflicts, but this does not seem to be the problem.
> 
> To further assist in resolving this issue quickly, I can provide the selector, JS path, full XPath of a message, and the last message of a group. I'm also willing to share a file containing the styles of these elements if it would be helpful.

Windows 11 Enterprise 23H2
Firefox Browser 124.0 (64 bit)
Privacy Extension For WhatsApp Web 3.1.0

**Comment by cruzy67** [comment]
Same Issue
OS : Windows 10 Pro 22H2 (64-bit)
Browser : Mozilla 124.0 (64-bit)
Privacy Extension For WhatsApp Web 3.1.0

**Comment by mclorand** [comment]
Is there a solution for Firefox?

**Comment by Tgentil** [comment]
> Is there a solution for Firefox?

https://www.youtube.com/watch?v=eyxNORJam5g&ab_channel=Skoottie

**Comment by mclorand** [comment]
> > Is there a solution for Firefox?
> 
> https://www.youtube.com/watch?v=eyxNORJam5g&ab_channel=SmartEnough

When I watched the video and cleaned cash, the plugin worked for a while, but then version 2.3000.1012344627 was installed and plugin doesn't work again. I think the problem is with the WhatsApp Web version. There is something preventing the plugin from working.

**Comment by Tgentil** [comment]
@mclorand , I've been experiencing similar issues with the extension on my end too. I find myself frequently needing to clear the cache to get the extension working again. It seems like the issue might be more complex than initially thought.

It's very frustrating having to clear the cache every time the page is refreshed, or the browser is closed and opened again. The worst part is having to log in every time after clearing the cache, which makes this task tiresome after doing it multiple times.

Continuously clearing the cache is a workaround, but an ideal solution would be a more permanent fix. Let's hope for a future update that resolves this.

**Comment by Ahmed-Soli** [comment]
> @mclorand , I've been experiencing similar issues with the extension on my end too. I find myself frequently needing to clear the cache to get the extension working again. It seems like the issue might be more complex than initially thought.
> 
> It's very frustrating having to clear the cache every time the page is refreshed, or the browser is closed and opened again. The worst part is having to log in every time after clearing the cache, which makes this task tiresome after doing it multiple times.
> 
> Continuously clearing the cache is a workaround, but an ideal solution would be a more permanent fix. Let's hope for a future update that resolves this.

can't agree more !

**Comment by devshekhawat** [comment]
> @mclorand , I've been experiencing similar issues with the extension on my end too. I find myself frequently needing to clear the cache to get the extension working again. It seems like the issue might be more complex than initially thought.
> 
> It's very frustrating having to clear the cache every time the page is refreshed, or the browser is closed and opened again. The worst part is having to log in every time after clearing the cache, which makes this task tiresome after doing it multiple times.
> 
> Continuously clearing the cache is a workaround, but an ideal solution would be a more permanent fix. Let's hope for a future update that resolves this.

@Tgentil @Ahmed-Soli I'm in the process of developing a lasting solution, but I'm exploring the possibility of a one-time subscription fee for the Pro solution. I'd like to gauge interest and see if people are open to paying for a permanent fix.

**Comment by aryomuzakki** [comment]
> 
> I have also tried disabling all other extensions to check for possible conflicts, but this does not seem to be the problem.

seems like whatsapp is giving a few updates that changes css again

My current environment that having an issue :
WhatsApp: v2.3000.1012436165
Browser : Brave v1.64.113 with Chromium v123.0.6312.86
OS: Windows 10 22H2 64Bit Build 19045.4170
Extension: v3.1.0


> 
> To further assist in resolving this issue quickly, I can provide the selector, JS path, full XPath of a message, and the last message of a group. I'm also willing to share a file containing the styles of these elements if it would be helpful.

I wanted to try to give PR and I just finished getting the selector for the last message and user/group name before reading this. Maybe if you have a selector for other elements like chat, can you share it ? It could be a nice help. @Tgentil 

I also want to suggest, how about having a fallback for when this kind of thing happen again. One switch that will blur something more general, or just blur the body instead. So someone will have some time to update extension.
Blur body seems simpler and could work with "Unblur All on App Hover"
@LukasLen ...

**Comment by techsamy** [comment]
This solution works for me. !!

![image](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/13311316/e5ba75da-d754-448c-ad18-56753ab65347)

**Comment by Usama171** [comment]
> Hello everyone,
> 
> I've found a solution that seems to work. I saw a similar issue in [#57](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/57#issuecomment-2017413671) where clearing the cache was suggested. I tried this, and it worked for me!
> 
> Here's what you can do:
> 
> 1. Open Chrome DevTools (`F12` or `Ctrl+Shift+I`).
> 2. Go to the `Application` tab.
> 3. Under the `Storage` section on the left, select `Clear storage`.
> 4. Clear site data.
> 
> This action should log you out of WhatsApp Web. Log back in, and the extension should start functioning normally again. I'm attaching a screenshot for reference.
> 
> ![Clear Cache in DevTools](https://private-user-images.githubusercontent.com/88681055/316508867-c1acae05-0bf7-4751-96af-8ecb2cbaeec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDUzMDYsIm5iZiI6MTcxMjA0NTAwNiwicGF0aCI6Ii84ODY4MTA1NS8zMTY1MDg4NjctYzFhY2FlMDUtMGJmNy00NzUxLTk2YWYtOGVjYjJjYmFlZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA4MDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDJiYjkzNTRlN2YxNDYwYzlkYjA2NmMwMjU5YjgwMDlhZGZlM2Q4M2RmNDU3NWExNTg2YzE5YzFjZGU1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-hK6JSeBt7oHc_hjf-1OD7ec27owwN29UxlT2XacBg)
> 
> Thanks to @Ahmed-Soli for the suggestion in the other issue. I'm closing this issue as resolved.
> 
> Best regards, Thiago Gentil

**Comment by devshekhawat** [comment]
This is temporary fix.
Once you refresh the page you'll see this issue again.

**Comment by amithm7** [comment]
There should be a better way to approach targeting CSS elements other than hard-coding randomly generated CSS classes in this extension.

**Comment by Tgentil** [comment]
It seems the issue I raised in [#56](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/56) and adressed in [#57](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/57) and [#60](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/60) about the extension not blurring might be resolved with the PR [#61](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/pull/61) submitted by @aritrakrbasu. For those still facing this issue, I suggest interacting with the PR through reactions and subscribing to it. This will bring more attention to the PR and potentially expedite its implementation. It's a good way for the community to show the repository owner the importance and demand for this solution.

**Comment by Ahmed-Soli** [comment]
> It seems the issue I raised in [#56](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/56) and adressed in [#57](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/57) and [#60](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/60) about the extension not blurring might be resolved with the PR [#61](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/pull/61) submitted by @aritrakrbasu. For those still facing this issue, I suggest interacting with the PR through reactions and subscribing to it. This will bring more attention to the PR and potentially expedite its implementation. It's a good way for the community to show the repository owner the importance and demand for this solution.

@Tgentil  Thanks for pointing this out, I tested the edits and it seems the blur is working fine even not blurring the account image is a nice touch, I liked it, however, the extension toggles buttons are not working and if I clicked on Toggle it will unblur and pressing it again does nothing , I must reload the page to get it to work again.

**Comment by Tgentil** [comment]
@aryomuzakki, thank you for the PR; I really appreciate the fixes you've made! I'm currently using your version until the repository gets updated. For those interested in a solution for this issue, I encourage you to check out and support PR [#66](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/pull/66). Your engagement can help highlight its effectiveness and might expedite its integration into the main repository.
