### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by Spacetaxfiling** [LukasLen/Privacy-Extension-For-WhatsApp-Web#57]
Hello Team,

The extension is not working..Blur is not working..

please fix the issue.

**Comment by GodAnt12** [comment]
Hello Team,

Extension not working..Blur not working..

I always use this extension. please fix the problem.

Thank You.

**Comment by Ahmed-Soli** [comment]
Stopped working for me as well.

**Comment by Tgentil** [comment]
Hello @Spacetaxfiling and others,

I wanted to share that the solution suggested by @Ahmed-Soli worked for me in the same issue that I had ([#56](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/56)). Clearing the cache and storage from the site resolved the problem with the extension not blurring content.

I recommend trying this solution. If it works, it might be a good idea to close this issue as well.

Thanks again to @Ahmed-Soli for the helpful tip!

Best regards,
Thiago Gentil

**Comment by asim-hawklogix** [comment]
The solution suggested by @Ahmed-Soli is working for me. please give it a try. try to clear cache and storage it will fix this problem.

**Comment by vvarl0cks** [comment]
not working atm

**Comment by satishgadhave** [comment]
Not working for me
Using Ubuntu

**Comment by Tgentil** [comment]
It seems the issue I raised in https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/56 and adressed in https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/57 and https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/issues/60 about the extension not blurring might be resolved with the PR https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/pull/61 submitted by @aritrakrbasu. For those still facing this issue, I suggest interacting with the PR through reactions and subscribing to it. This will bring more attention to the PR and potentially expedite its implementation. It's a good way for the community to show the repository owner the importance and demand for this solution.
