### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by ticmaidev** [LukasLen/Privacy-Extension-For-WhatsApp-Web#62]
won't work on Firefox and Chrome

whatsapp went down for a few minutes around the world and now the extension won't work

**Comment by LivreAcessoPro** [comment]
Same here.
Which version? I'm using Firefox ESR (Debian Stable) and I can't update the extension. Minimum version 121, it says.

**Comment by URODESUKA** [comment]
same here won't work, maybe in the maintenance?

**Comment by aritrakrbasu** [comment]
@LivreAcessoPro @ticmaidev and @URODESUKA , I have addressed this issue and fixed the problem in #61 PR … As of now you can download the code from my repository and load the unpack version in your chrome, it will work fine. 

Do let me know it you need any help!

**Comment by LivreAcessoPro** [comment]
@aritrakrbasu I'm using Firefox ESR.
