### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by fabianodellano** [LukasLen/Privacy-Extension-For-WhatsApp-Web#64]
I use Chrome Version 123.0.6312.106 (Official version) 64 bits, Portuguese, Brazil, and it no longer blurs anything.

**Comment by TejasMishr** [comment]
i use Brave latest version and stopped working in India and no longer Blurs anything

**Comment by fabianodellano** [comment]
Congratulations, I updated it here and it's working perfectly!
