### ISSUE TITLE
whats app blur not working

### ISSUE THREAD

**Issue by mufeedkka** [LukasLen/Privacy-Extension-For-WhatsApp-Web#67]
whats app blur not working

**Comment by Tgentil** [comment]
Remove and reinstall the extension to update to the new version 3.2.0. You can do it using this link: [Privacy-Extension-For-WhatsApp-Web](https://chromewebstore.google.com/detail/extens%C3%A3o-de-privacidade-p/jbojhlhhggfmmkpefknmbdhlaghehini). This should fix your problem!
