### ISSUE TITLE
Little enhancements

### ISSUE THREAD

**Issue by Xarchuser** [LukasLen/Privacy-Extension-For-WhatsApp-Web#68]
I've made little bit adjustments since i use dark theme alot as in messages preview some kind of annoying little triangles popped up in blur messages as you can see below :

![1](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/29339012/16e3521e-6ee0-4677-8a0e-bb9171f53908)
also:
![2](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/29339012/38a2d2ad-0f4a-4827-a663-7d421deed3fa)
so i fixed this using the following CSS:

```
.message-out ._amk7
{
    right: 15px;
    top: 15px;
}

.message-in ._amk7
{
  left: 15px; 
  top: 15px;
}
```
I'm not a programmer so please fix my css if you have something in mind better than this haha.

also I'd like to show another little enhancement , I prefer to show the notifications number instead of blurring it so i can see how much messages i have and it caughts me attention whenever a new message pops up. 

![test](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/assets/29339012/5457da4e-a4ec-4133-b37a-2d42ec4b292d)

here is what i used in the code...:

```
._ak8k /*message preview*/
{
  filter: blur(8px) grayscale(1);
  transition-delay: 0s;
}


/* updated wa version (v2.3000.xx) */
._ak8k:hover /*message preview*/
{
  filter: blur(0px) grayscale(0);
  transition-delay: 0.3s;

```

do not to forget to :  `body:hover div._ak8k /* message preview */,` on unblurActive :D

Sorry for any code or english mistakes.

**Comment by Tgentil** [comment]
Enhancement added by #87
