### ISSUE TITLE
`v3.2.0`: "Read more" button gets hidden when "Media preview" setting is enabled.

### ISSUE THREAD

**Issue by amithm7** [LukasLen/Privacy-Extension-For-WhatsApp-Web#73]
**Describe the bug**

When "Media preview" filter / blur setting is enabled

> Long text...[Read more]()

becomes

> Long text...

**To Reproduce**

Send or receive a long text

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser FireFox
 - Version

**Comment by Tgentil** [comment]
Fixed in #87
