### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by rish15** [LukasLen/Privacy-Extension-For-WhatsApp-Web#76]
**Describe the bug**
After the new update of the whatsapp this extension stopped working

**To Reproduce**
1. Just install the extension and check 

**Expected behavior**
It should work out of box

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox & chrome
 - Version 126.0 (64-bit) firefox 
 - chrome Version 123.0.6312.106 (Official Build) (arm64)

**Comment by rish15** [comment]
I have reinstalled the extension, its working for now lemme observe it for couple of days

**Comment by Tgentil** [comment]
@rish15, it looks like reinstalling the extension has resolved the issue for you. For future reference, could you please confirm the current version of WhatsApp you are using? The extension is functioning correctly for me in Version 2.3000.1013681929.

Additionally, here is a update that may shed some light on recent changes that temporarily affected the extension's functionality: [Update to support WhatsApp Version 2.3000.xx](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/commit/20c4729970fa500437ae33b41a05bae4cfbcdeb3).
