### ISSUE TITLE
Un-blur message count badge

### ISSUE THREAD

**Issue by saliaku** [LukasLen/Privacy-Extension-For-WhatsApp-Web#80]
**Is your feature request related to a problem? Please describe.**
When someone sends a new message , the badge that shows the unread messages is also blurred. can lead to missing out on some messages

**Describe the solution you'd like**
Un-blur this part by default or make a toggle for it.

**Describe alternatives you've considered**
Alternatively I can toggle the last message preview on/off but it comes with a conflict of interest , the privacy of recent messages would be gone.

**Additional context**
![image](https://github.com/user-attachments/assets/a9ac8d67-b998-4896-a8e8-a24282805fd3)
![Screenshot from 2024-08-16 03-24-58](https://github.com/user-attachments/assets/3ec55c37-e6a9-402a-a240-95124f9ee601)
the green message counter at the right

**Comment by Tgentil** [comment]
Fixed in #87
