### ISSUE TITLE
 Urgent: WhatsApp Privacy Extension Not Functioning Properly

### ISSUE THREAD

**Issue by shoaib277** [LukasLen/Privacy-Extension-For-WhatsApp-Web#81]
Subject: Urgent: WhatsApp Privacy Extension Not Functioning Properly

Dear [Support Team/Customer Service],

I hope this message finds you well. I am writing to report an issue with your WhatsApp Privacy Extension. Unfortunately, the extension is not functioning as expected, particularly concerning profile pictures and user/group names. Despite enabling the privacy settings, the extension fails to conceal or manage these elements effectively.

This is a critical feature for maintaining my privacy, and I kindly request that your team addresses this issue as soon as possible. Please provide an update on the status of this fix and any necessary steps I should take on my end.

**Comment by shoaib277** [comment]
![Uploading image.p
![Screenshot 2024-08-23 122651](https://github.com/user-attachments/assets/ad357798-154a-4acc-94a9-2623d0859850)
ng…]()


![Uploading image.png…]()

**Comment by shoaib277** [comment]
ok

**Comment by Vladeouz** [comment]
any solution for this ?

**Comment by Tgentil** [comment]
@shoaib277 Could you please provide new screenshots to demonstrate the issue you're facing? Unfortunately, the screenshots you previously uploaded are not loading on my machine, so we are unable to identify correctly the problem. 

This will help us better understand the issue and work towards a solution.

**Comment by Tgentil** [comment]
Fixed on #87
