### ISSUE TITLE
Name Title Unblur

### ISSUE THREAD

**Issue by HumzaSubhani** [LukasLen/Privacy-Extension-For-WhatsApp-Web#82]
Extension not working properly. Name Title is unblured.
 
![Screenshot (77)](https://github.com/user-attachments/assets/2d7f6898-164a-4e60-b701-ff5b56e8d616)

**Comment by HumzaSubhani** [comment]
Have deleted and installed again but still not working properly.

**Comment by LukasLen** [comment]
Duplicate of #81
