### ISSUE TITLE
A slight delay to unblur any message

### ISSUE THREAD

**Issue by malikariefa** [LukasLen/Privacy-Extension-For-WhatsApp-Web#90]
**Describe the bug**
Hi, in version 3.3.0 I think the hover time needed to unblur all messages is too long. Before this update, it used to be instantaneou. However, now i have to wait about 100-200 ms, which is a significant time increase.

**To Reproduce**
Hover any blurred message in v3.3.0

**Expected behavior**
instantly unblur hovered message

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 130.0

**Whatsapp Web Version (please complete the following information):**
 - Version: 2.3000.1016224148

**Comment by Tgentil** [comment]
@malikariefa 

Have you considered enabling the "No transition delay" option?

![2024-09-05_11h30_58](https://github.com/user-attachments/assets/e97df2f7-00ec-4164-9383-33eea11bf2eb)
> My extension is in pt_BR, but the option in english should be: "No transition delay".

This might solve the issue you're experiencing with the delay in unblurring messages. Let me know if it helps!

**Comment by malikariefa** [comment]
Hi! thank you very much, this actually
